
all :
	cd proto/ && make
	cd server/ && make
	cd client/ && make

schema :
	cd proto/ && make

server :
	cd server/ && make

client :
	cd client/ && make


clean :
	cd proto/ && make clean
	cd server/ && make clean
	cd client/ && make clean
