// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: nfs.proto

#include "nfs.pb.h"
#include "nfs.grpc.pb.h"

#include <functional>
#include <grpcpp/impl/codegen/async_stream.h>
#include <grpcpp/impl/codegen/async_unary_call.h>
#include <grpcpp/impl/codegen/channel_interface.h>
#include <grpcpp/impl/codegen/client_unary_call.h>
#include <grpcpp/impl/codegen/client_callback.h>
#include <grpcpp/impl/codegen/method_handler_impl.h>
#include <grpcpp/impl/codegen/rpc_service_method.h>
#include <grpcpp/impl/codegen/server_callback.h>
#include <grpcpp/impl/codegen/service_type.h>
#include <grpcpp/impl/codegen/sync_stream.h>
namespace NFS {

static const char* nfsServer_method_names[] = {
  "/NFS.nfsServer/call",
};

std::unique_ptr< nfsServer::Stub> nfsServer::NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options) {
  (void)options;
  std::unique_ptr< nfsServer::Stub> stub(new nfsServer::Stub(channel));
  return stub;
}

nfsServer::Stub::Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel)
  : channel_(channel), rpcmethod_call_(nfsServer_method_names[0], ::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  {}

::grpc::Status nfsServer::Stub::call(::grpc::ClientContext* context, const ::NFS::request& request, ::NFS::response* response) {
  return ::grpc::internal::BlockingUnaryCall(channel_.get(), rpcmethod_call_, context, request, response);
}

void nfsServer::Stub::experimental_async::call(::grpc::ClientContext* context, const ::NFS::request* request, ::NFS::response* response, std::function<void(::grpc::Status)> f) {
  return ::grpc::internal::CallbackUnaryCall(stub_->channel_.get(), stub_->rpcmethod_call_, context, request, response, std::move(f));
}

void nfsServer::Stub::experimental_async::call(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::NFS::response* response, std::function<void(::grpc::Status)> f) {
  return ::grpc::internal::CallbackUnaryCall(stub_->channel_.get(), stub_->rpcmethod_call_, context, request, response, std::move(f));
}

::grpc::ClientAsyncResponseReader< ::NFS::response>* nfsServer::Stub::AsynccallRaw(::grpc::ClientContext* context, const ::NFS::request& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderFactory< ::NFS::response>::Create(channel_.get(), cq, rpcmethod_call_, context, request, true);
}

::grpc::ClientAsyncResponseReader< ::NFS::response>* nfsServer::Stub::PrepareAsynccallRaw(::grpc::ClientContext* context, const ::NFS::request& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderFactory< ::NFS::response>::Create(channel_.get(), cq, rpcmethod_call_, context, request, false);
}

nfsServer::Service::Service() {
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      nfsServer_method_names[0],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< nfsServer::Service, ::NFS::request, ::NFS::response>(
          std::mem_fn(&nfsServer::Service::call), this)));
}

nfsServer::Service::~Service() {
}

::grpc::Status nfsServer::Service::call(::grpc::ServerContext* context, const ::NFS::request* request, ::NFS::response* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}


}  // namespace NFS

